# Generated by Django 6.0.3 on 2026-03-10 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='минимум пять символов'), django.core.validators.MaxLengthValidator(100, message='максимум пять символов')], verbose_name='Slug'),
        ),
    ]
